### ISSUE TITLE
KeyError 'request'

### ISSUE THREAD

**Issue by tnightengale** [TitorX/Postdown#10]
Running on Postman v0.2 Collection (including folders) results in a strange KeyError:
```
Traceback (most recent call last):
  File "/usr/local/bin/postdown", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.9/site-packages/postdown/cmdline.py", line 14, in execute
    parse(in_file, out_file)
  File "/usr/local/lib/python3.9/site-packages/postdown/parser.py", line 28, in parse
    request = api['request']
KeyError: 'request'
```

**Comment by xiaorui16888** [comment]
我也遇到了这个问题
![image](https://user-images.githubusercontent.com/24950780/147597015-3686ac1b-cbad-429b-81ba-a682e67024b5.png)

**Comment by xiaorui16888** [comment]
我也遇到了这个问题
![image](https://user-images.githubusercontent.com/24950780/147597015-3686ac1b-cbad-429b-81ba-a682e67024b5.png)

**Comment by edneyrafael** [comment]
I get the same issue.

**Comment by Mehrdad-Dadkhah** [comment]
+1

**Comment by therealsteveg** [comment]
samesies

**Comment by santosh-od** [comment]
any solution yet?

**Comment by bagabool** [comment]
made a [package](https://github.com/bagabool/palourde) that should work on every v2.1 collection
