### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32886: character maps to <undefined>

### ISSUE THREAD

**Issue by shahind** [TitorX/Postdown#11]
On collection V2 and V2.1 I get this error
```
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\Scripts\postdown-script.py", line 33, in <module>
    sys.exit(load_entry_point('Postdown==1.0.11', 'console_scripts', 'postdown')())
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\postdown\cmdline.py", line 14, in execute
    parse(in_file, out_file)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\postdown\parser.py", line 16, in parse
    collection = json.load(f)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32886: character maps to <undefined>
```

**Comment by wisnuwirayuda15** [comment]
Don't use emoji on your description or other text field
