### ISSUE TITLE
I ma getting an error converting v2 collection to MD

### ISSUE THREAD

**Issue by bjrshussain** [TitorX/Postdown#12]
Traceback (most recent call last):
  File "/usr/local/bin/postdown", line 8, in <module>
    sys.exit(execute())
  File "/home/bjrshussain/.local/lib/python3.10/site-packages/postdown/cmdline.py", line 14, in execute
    parse(in_file, out_file)
  File "/home/bjrshussain/.local/lib/python3.10/site-packages/postdown/parser.py", line 28, in parse
    request = api['request']
KeyError: 'request'

**Comment by alimi-ajibade** [comment]
It seems there's a version discrepancy between the package downloaded via pip and the code available on GitHub. To resolve this, you can follow these steps: First, install the package. Then, download the code from GitHub. Next, replace the 'postdown' folder in the package with the one you downloaded from GitHub. After completing these steps, try the conversion process again.
