### ISSUE TITLE
Does not work if there is a blank description

### ISSUE THREAD

**Issue by cdgriffith** [TitorX/Postdown#4]
https://github.com/TitorX/Postdown/blob/master/postdown/parser.py#L21

Should be updated to use `.get('description', '')`

**Comment by jonasbn** [comment]
I observe this issue too, this is the error message.

```
Traceback (most recent call last):
  File "/usr/local/bin/postdown", line 10, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/site-packages/postdown/cmdline.py", line 14, in execute
    parse(in_file, out_file)
  File "/usr/local/lib/python2.7/site-packages/postdown/parser.py", line 34, in parse
    doc.block(request['description'])
KeyError: 'description'
```

**Comment by samcrane8** [comment]
I'm currently waiting for TitorX to review my pull request, but in the meantime you can checkout my fork [here](https://github.com/samcrane8/Postdown), it handles this issue.

It's not on pip though so you have to clone the source.

**Comment by askme-gpt** [comment]
I solved this bug ,and become it a pip package.  https://github.com/ShuiPingYang/YspPostdown

**Comment by Gauhar** [comment]
@ShuiPingYang  - This is still happening for me and I am getting the following error:

```
File "/opt/homebrew/bin/postdown", line 8, in <module>
    sys.exit(execute())
  File "/opt/homebrew/lib/python3.9/site-packages/postdown/cmdline.py", line 14, in execute
    parse(in_file, out_file)
  File "/opt/homebrew/lib/python3.9/site-packages/postdown/parser.py", line 21, in parse
    doc.line(collection['info']['description'])
KeyError: 'description'
```

On parser.py line 21 still expects to have description 

```
rows = get_rows(
            request['url']['query'],
            ['key', 'value', 'description']
        )
```

**Comment by jonasbn** [comment]
@Gauhar I think @ShuiPingYang has released a (new) separate package: [ysp-postdown](https://pypi.org/project/ysp-postdown/)

See [pypi.org](https://pypi.org/search/?q=postdown), so this package ([Postdown](https://pypi.org/project/Postdown/)) has not been updated, but there is an alternative ([ysp-postdown](https://pypi.org/project/ysp-postdown/)).

**Comment by rsm-dnierman** [comment]
I am getting this error with [ysp-postdown](https://pypi.org/project/ysp-postdown/)

```
Traceback (most recent call last):
  File "/usr/local/bin/ysp_postdown", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.9/site-packages/ysp_postdown/cmdline.py", line 14, in execute
    parse(in_file, out_file)
  File "/usr/local/lib/python3.9/site-packages/ysp_postdown/parser.py", line 42, in parse
    request = api['request']
KeyError: 'request'
```

**Comment by cdgriffith** [comment]
Closing due to lack of activity on this repo
